version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.1
    - 1.4.0
  - dependency-name: pry
    versions:
    - 0.14.0
